// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Application;
using Infrastructure.Context;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230217121759_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.Property<int>("EquipmentsID")
                        .HasColumnType("integer");

                    b.Property<int>("ExercisesID")
                        .HasColumnType("integer");

                    b.HasKey("EquipmentsID", "ExercisesID");

                    b.HasIndex("ExercisesID");

                    b.ToTable("ExercisesEquipments", (string)null);
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.Property<int>("ExercisesID")
                        .HasColumnType("integer");

                    b.Property<int>("MusclesID")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesID", "MusclesID");

                    b.HasIndex("MusclesID");

                    b.ToTable("ExerciseMuscle");
                });

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("ExercisesID")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroupsID")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesID", "MuscleGroupsID");

                    b.HasIndex("MuscleGroupsID");

                    b.ToTable("ExercisesMuscleGroups", (string)null);
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.Property<int>("ExercisesID")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutsID")
                        .HasColumnType("uuid");

                    b.HasKey("ExercisesID", "WorkoutsID");

                    b.HasIndex("WorkoutsID");

                    b.ToTable("WorkoutsExercises", (string)null);
                });

            modelBuilder.Entity("MuscleMuscleGroup", b =>
                {
                    b.Property<int>("MuscleGroupsID")
                        .HasColumnType("integer");

                    b.Property<int>("MusclesID")
                        .HasColumnType("integer");

                    b.HasKey("MuscleGroupsID", "MusclesID");

                    b.HasIndex("MusclesID");

                    b.ToTable("MusclesMuscleGroups", (string)null);
                });

            modelBuilder.Entity("WorkoutWorkoutRoutine", b =>
                {
                    b.Property<Guid>("WorkoutRoutineID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkoutsID")
                        .HasColumnType("uuid");

                    b.HasKey("WorkoutRoutineID", "WorkoutsID");

                    b.HasIndex("WorkoutsID");

                    b.ToTable("WorkoutRoutinesWorkouts", (string)null);
                });

            modelBuilder.Entity("api.Entities.IEquipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("api.Entities.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("api.Entities.IMuscle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("api.Entities.IMuscleGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("api.Entities.IUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccountCreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAuthenticationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isVerified")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Entities.IWorkout", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccesibilityLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("workout_owner")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("workout_owner");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("api.Entities.IWorkoutRoutine", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccesibilityLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("workoutroutine_owner")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("workoutroutine_owner");

                    b.ToTable("WorkoutRoutines");
                });

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.HasOne("api.Entities.IEquipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.HasOne("api.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.IMuscle", null)
                        .WithMany()
                        .HasForeignKey("MusclesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.HasOne("api.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.IMuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.HasOne("api.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.IWorkout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuscleMuscleGroup", b =>
                {
                    b.HasOne("api.Entities.IMuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.IMuscle", null)
                        .WithMany()
                        .HasForeignKey("MusclesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutWorkoutRoutine", b =>
                {
                    b.HasOne("api.Entities.IWorkoutRoutine", null)
                        .WithMany()
                        .HasForeignKey("WorkoutRoutineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.IWorkout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.IWorkout", b =>
                {
                    b.HasOne("api.Entities.IUser", "Owner")
                        .WithMany("Workouts")
                        .HasForeignKey("workout_owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("api.Entities.IWorkoutRoutine", b =>
                {
                    b.HasOne("api.Entities.IUser", "Owner")
                        .WithMany("WorkoutRoutines")
                        .HasForeignKey("workoutroutine_owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("api.Entities.IUser", b =>
                {
                    b.Navigation("WorkoutRoutines");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
